SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `patient`;
DROP TABLE IF EXISTS `exploration`;
DROP TABLE IF EXISTS `report`;
DROP TABLE IF EXISTS `requestedexploration`;
DROP TABLE IF EXISTS `performedexploration`;
DROP TABLE IF EXISTS `explorationcode`;
DROP TABLE IF EXISTS `radiograph`;
DROP TABLE IF EXISTS `signtype`;
DROP TABLE IF EXISTS `sign`;
DROP TABLE IF EXISTS `signlocation`;

SET FOREIGN_KEY_CHECKS = 1;
